In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3])

In [5]:
import pandas as pd 

df = pd.DataFrame([[1,2,3],[4,5,6],[4,5,0],[2,4,5]], columns=['X','Y','Z'])

In [6]:
df = df.rename(index={0: 'A',1: 'B',2: 'C', 3: 'D'} )
df


X  Y  Z
A  1  2  3
B  4  5  6
C  4  5  0
D  2  4  5

In [7]:
df_t = df.T
df_t

A  B  C  D
X  1  4  4  2
Y  2  5  5  4
Z  3  6  0  5

In [8]:
df_t[['A', "B"]] - df['X'][['A', "B"]]

A  B
X  0  0
Y  1  1
Z  2  2

In [9]:
df_t['A'] - df['X']

A   NaN
B   NaN
C   NaN
D   NaN
X   NaN
Y   NaN
Z   NaN
dtype: float64

In [13]:
arr = np.random.randn(5,3)
arr

array([[-0.38279174, -1.16081177, -1.57790652],
       [-0.07162246,  0.61794725,  0.99505982],
       [ 0.39942693, -1.43150781, -0.1714556 ],
       [ 0.43777146,  0.82353527, -2.2751718 ],
       [-0.60689087,  1.15353827, -0.41710551]])

In [15]:
arr.sort(1)
arr

array([[-1.57790652, -1.16081177, -0.38279174],
       [-0.07162246,  0.61794725,  0.99505982],
       [-1.43150781, -0.1714556 ,  0.39942693],
       [-2.2751718 ,  0.43777146,  0.82353527],
       [-0.60689087, -0.41710551,  1.15353827]])

In [16]:
arr = np.random.randn(5,3)
arr

array([[-0.30710575, -0.68730615,  0.01245462],
       [ 0.5779513 , -0.62191326,  0.67407613],
       [-0.13427026, -0.02872711, -1.64149063],
       [-0.29592965,  0.96866766, -1.15205238],
       [ 1.15394376, -0.28810141, -1.96159514]])

In [17]:
np.sort(arr)

array([[-0.68730615, -0.30710575,  0.01245462],
       [-0.62191326,  0.5779513 ,  0.67407613],
       [-1.64149063, -0.13427026, -0.02872711],
       [-1.15205238, -0.29592965,  0.96866766],
       [-1.96159514, -0.28810141,  1.15394376]])

In [18]:
arr

array([[-0.30710575, -0.68730615,  0.01245462],
       [ 0.5779513 , -0.62191326,  0.67407613],
       [-0.13427026, -0.02872711, -1.64149063],
       [-0.29592965,  0.96866766, -1.15205238],
       [ 1.15394376, -0.28810141, -1.96159514]])

In [20]:
arr.sort()
arr

array([[-0.68730615, -0.30710575,  0.01245462],
       [-0.62191326,  0.5779513 ,  0.67407613],
       [-1.64149063, -0.13427026, -0.02872711],
       [-1.15205238, -0.29592965,  0.96866766],
       [-1.96159514, -0.28810141,  1.15394376]])

In [23]:
arr[int(0.05 * len(arr))]

array([-0.68730615, -0.30710575,  0.01245462])